//Message
export const GET_RECORDS = 'GET_RECORDS';
export const SET_RECORDS = 'SET_RECORDS';
export const INSERT_RECORD = 'INSERT_RECORD';
export const SET_FAVOURITES = 'SET_FAVOURITES';
export const GET_FAVOURITES = 'GET_FAVOURITES';
export const DELETE_FAVOURITE = 'DELETE_FAVOURITE';
export const INSERT_FAVOURITES = 'INSERT_FAVOURITES';
export const SEARCH_ARTICLES = 'SEARCH_ARTICLES';
